name: cuid2
description: A dart implementaion of the secure, collision-resistant ids optimized for horizontal scaling and performance (v2). 
version: 1.0.0
homepage: https://github.com/obsidiaHQ/cuid2
repository: https://github.com/obsidiaHQ/cuid2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  pointycastle: ^3.6.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
